### ISSUE TITLE
M3 Note Kernel Source

### ISSUE THREAD

**Issue by scafroglia93** [meizuosc/m576#3]
Please, release this kernel source

**Comment by ghost** [comment]
Meizu stated somewhere they release kernel for devices a few months after release (translation : when the m4 note will be announced :P )

**Comment by meizuosc** [comment]
@scafroglia93 We have received your request, and will release m3note kernel source under GPLv2 ASAP.

Thanks.

**Comment by ghost** [comment]
M4 note confirmed ?

**Comment by scafroglia93** [comment]
Bootloader is locked

**Comment by rentocika** [comment]
What about unlock bootloader for those who want unlock?
